### ISSUE TITLE
New CI workflow

### ISSUE THREAD

**Issue by tammasloughran** [tammasloughran/ehfheatwaves#17]
The old Travis CI workflow is no longer used by github. Set up a new one.

```
name: ehfheatwaves

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: |
          git clone https://github.com/tammasloughran/ehfheatwaves
          cd ehfheatwaves/tests
          python run_tests.py
```
